CREATE EXTENSION IF NOT EXISTS CITEXT;

CREATE TABLE IF NOT EXISTS users (
  id SERIAL NOT NULL PRIMARY KEY,
  nickname CITEXT NOT NULL UNIQUE,
  fullname CITEXT,
  email CITEXT NOT NULL UNIQUE,
  about TEXT);

CREATE TABLE IF NOT EXISTS forums (
  id SERIAL NOT NULL PRIMARY KEY,
  title CITEXT NOT NULL,
  user_id INT NOT NULL,
  slug CITEXT NOT NULL UNIQUE,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS threads (
  id SERIAL NOT NULL PRIMARY KEY,
  title CITEXT NOT NULL,
  user_id INT NOT NULL,
  forum_id INT NOT NULL,
  message CITEXT NOT NULL,
  slug CITEXT NOT NULL UNIQUE,
  created TIMESTAMP DEFAULT NOW(),
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL,
  FOREIGN KEY (forum_id) REFERENCES forums (id) ON DELETE SET NULL
);
